# Generated by Django 4.2.3 on 2023-07-22 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gustos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gustos', models.CharField(max_length=150)),
                ('seleccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'db_table': 'Tarea',
            },
        ),
    ]
