# Generated by Django 4.2.3 on 2023-07-22 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_gustos'),
    ]

    operations = [
        migrations.CreateModel(
            name='gustos2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gustos', models.CharField(max_length=150)),
                ('seleccion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'tarea1',
                'verbose_name_plural': 'tareas1',
                'db_table': 'Tarea1',
            },
        ),
        migrations.DeleteModel(
            name='gustos',
        ),
    ]
