# Generated by Django 4.2.3 on 2023-07-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_gustos2_delete_gustos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gustos2',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tarea'},
        ),
        migrations.AlterModelTable(
            name='gustos2',
            table='Tarea',
        ),
    ]
