# Generated by Django 4.2.3 on 2023-07-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_alter_gustos2_options_alter_gustos2_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gustos2',
            new_name='Tarea',
        ),
    ]
